### PR TITLE
Update options.from modification for nodemailer

### PR DESCRIPTION
**Pull request by sudosteve**
Code incorrectly uses options.from twice instead of options.from options.user

### CODE REVIEW

**Comment by alexgvozden** [comment]
this should be merged as it relieves the bug using from

**Review by reqshark — APPROVED** [review]

**Comment by reqshark** [comment]
backup has now arrived on scene but its like years after the crime

🚓 🚓 🚓 

the `gmail-send` program is broken and unsuable without this PR.

the `from` text is completely ruined when you send email, and it's been like that forever

personally i have applied this patch in my software the whole time

but if this ever got merged 🔥:fire: :fire:

I could stop using the patch from this PR and switch back to this project 🚀

**Comment by honeymaro** [comment]
Please merge this.

**Comment by softremake** [comment]
@alykoshin Almost 3 years since this patch was made but new users still have to dig into the code to figure out why it's not working...

**Comment by gabrielmaldi** [comment]
This fixes the bug which prevents setting the `from` name.

**Comment by gabrielmaldi** [comment]
Thanks a lot, @alykoshin! 🚀

**Comment by alykoshin** [comment]
you are welcome.
@all, sorry for long silence.

**Comment by gabrielmaldi** [comment]
Is there a release to npm planned? Thanks again.

**Comment by alykoshin** [comment]
Also updated dependencies to latest versions; you may upgrade to `gmail-send@1.8.14`.

**Comment by reqshark** [comment]
oh great, glad to see this one landed. thanks @alykoshin

**Pull request merged**
